[package]
name = "roxt"
version = "0.1.0"
authors = ["Trevor Arjeski <tmarjeski@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
argh = "0.1.3"
thiserror = "1.0"